########################################################################################
# Config
########################################################################################

# trunk-ignore-all(yamllint/empty-values)

volumes:
  genesis-switchlynode:
  genesis-bifrost:
  validator-1-switchlynode:
  validator-1-bifrost:
  validator-2-switchlynode:
  validator-2-bifrost:
  validator-3-switchlynode:
  validator-3-bifrost:

########################################################################################
# Services
########################################################################################

services:
  _switchly: &switchly-defaults
    profiles:
      - _
    restart: unless-stopped
    image: registry.gitlab.com/switchly/switchlynode:stagenet-2.137.3
    environment: &switchly-environment
      NET: stagenet
      CHAIN_ID: switchly
      SIGNER_NAME: switchly
      SIGNER_PASSWD: password
      SWITCHLY_SEED_NODES_ENDPOINT: ""

      # "dog" mnemonic addresses for faucet
      FAUCET: sthor1zf3gsk7edzwl9syyefvfhle37cjtql3585mpmq

      # reuse stagenet router contract deployments, or deploy your own new ones
      ETH_CONTRACT: "0xa8D1Ff3bfA490cf7890D0D2C0A2f5815744A279F"
      XLM_CONTRACT: "CC7XNCYBCI2UVAE2A5TUBALEXMZXTYHLMKYOA6FSXVRT42YLR76NQR7R" # testnet

  ######################################################################################
  # Genesis
  ######################################################################################

  # ------------------------------ switchlynode ------------------------------

  genesis-switchlynode: &genesis-switchlynode
    <<: *switchly-defaults
    profiles:
      - genesis
    ports:
      - 27147:27147
      - 27146:27146
      - 1317:1317
      - 6060:6060
    volumes:
      - ./mnt:/mnt
      - genesis-switchlynode:/root/.switchlynode
    entrypoint: /scripts/genesis.sh

    environment: &genesis-switchlynode-environment
      <<: *switchly-environment
      SEED: switchlynode

  # ------------------------------ bifrost ------------------------------

  genesis-bifrost: &genesis-bifrost
    <<: *switchly-defaults

    profiles:
      - genesis
    ports:
      - 5040:5040
      - 6040:6040
    entrypoint: /scripts/bifrost.sh
    volumes:
      - genesis-bifrost:/var/data/bifrost
      - genesis-switchlynode:/root/.switchlynode
    command: ["bifrost"]

    environment: &genesis-bifrost-environment
      <<: *switchly-environment

      CHAIN_API: genesis-switchlynode:1317
      CHAIN_RPC: genesis-switchlynode:27147
      BIFROST_SWITCHLYCHAIN_CHAIN_EBIFROST: genesis-switchlynode:50051

      BIFROST_CHAINS_AVAX_DISABLED: "false"
      BIFROST_CHAINS_AVAX_RPC_HOST: https://api.avax.network/ext/bc/C/rpc

      BIFROST_CHAINS_GAIA_DISABLED: "true"
      BIFROST_CHAINS_GAIA_RPC_HOST: ""
      BIFROST_CHAINS_GAIA_COSMOS_GRPC_HOST: ""

      BIFROST_CHAINS_BSC_DISABLED: "true"
      BIFROST_CHAINS_BSC_RPC_HOST: ""

      BIFROST_CHAINS_BASE_DISABLED: "true"
      BIFROST_CHAINS_BASE_RPC_HOST: ""

      BIFROST_CHAINS_BTC_DISABLED: "true"
      BIFROST_CHAINS_BTC_RPC_HOST: ""

      BIFROST_CHAINS_DOGE_DISABLED: "true"
      BIFROST_CHAINS_DOGE_RPC_HOST: ""

      BIFROST_CHAINS_BCH_DISABLED: "true"
      BIFROST_CHAINS_BCH_RPC_HOST: ""

      BIFROST_CHAINS_LTC_DISABLED: "true"
      BIFROST_CHAINS_LTC_RPC_HOST: ""

      BIFROST_CHAINS_ETH_DISABLED: "true"
      BIFROST_CHAINS_ETH_RPC_HOST: ""

  ######################################################################################
  # Validator-1
  ######################################################################################

  validator-1-switchlynode: &validator-1-switchlynode
    <<: *genesis-switchlynode
    profiles:
      - validator-1
    ports: []
    environment: &validator-1-switchlynode-environment
      <<: *genesis-switchlynode-environment
      PEER: genesis-switchlynode
      SEEDS: genesis-switchlynode
    volumes:
      - ./mnt:/mnt
      - validator-1-switchlynode:/root/.switchlynode
    entrypoint: /scripts/validator.sh

  validator-1-bifrost: &validator-1-bifrost
    <<: *genesis-bifrost
    profiles:
      - validator-1
    environment: &validator-1-bifrost-environment
      <<: *genesis-bifrost-environment
      PEER: genesis-bifrost
      CHAIN_API: validator-1-switchlynode:1317
      CHAIN_RPC: validator-1-switchlynode:27147
      BIFROST_SWITCHLYCHAIN_CHAIN_EBIFROST: validator-1-switchlynode:50051
    ports:
      - 5040
      - 6040
    volumes:
      - validator-1-bifrost:/var/data/bifrost
      - validator-1-switchlynode:/root/.switchlynode

  ######################################################################################
  # Validator-2
  ######################################################################################

  validator-2-switchlynode:
    <<: *validator-1-switchlynode
    profiles:
      - validator-2
    ports: []
    environment:
      <<: *validator-1-switchlynode-environment
    volumes:
      - ./mnt:/mnt
      - validator-2-switchlynode:/root/.switchlynode

  validator-2-bifrost:
    <<: *validator-1-bifrost
    profiles:
      - validator-2
    environment:
      <<: *validator-1-bifrost-environment
      CHAIN_API: validator-2-switchlynode:1317
      CHAIN_RPC: validator-2-switchlynode:27147
      BIFROST_SWITCHLYCHAIN_CHAIN_EBIFROST: validator-2-switchlynode:50051
    volumes:
      - validator-2-bifrost:/var/data/bifrost
      - validator-2-switchlynode:/root/.switchlynode

  ######################################################################################
  # Validator-3
  ######################################################################################

  validator-3-switchlynode:
    <<: *validator-1-switchlynode
    profiles:
      - validator-3
    ports: []
    environment:
      <<: *validator-1-switchlynode-environment
    volumes:
      - ./mnt:/mnt
      - validator-3-switchlynode:/root/.switchlynode

  validator-3-bifrost:
    <<: *validator-1-bifrost
    profiles:
      - validator-3
    environment:
      <<: *validator-1-bifrost-environment
      CHAIN_API: validator-3-switchlynode:1317
      CHAIN_RPC: validator-3-switchlynode:27147
      BIFROST_SWITCHLYCHAIN_CHAIN_EBIFROST: validator-3-switchlynode:50051
    volumes:
      - validator-3-bifrost:/var/data/bifrost
      - validator-3-switchlynode:/root/.switchlynode
