// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package types

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_QueryNetworkRequest        protoreflect.MessageDescriptor
	fd_QueryNetworkRequest_height protoreflect.FieldDescriptor
)

func init() {
	file_types_query_network_proto_init()
	md_QueryNetworkRequest = File_types_query_network_proto.Messages().ByName("QueryNetworkRequest")
	fd_QueryNetworkRequest_height = md_QueryNetworkRequest.Fields().ByName("height")
}

var _ protoreflect.Message = (*fastReflection_QueryNetworkRequest)(nil)

type fastReflection_QueryNetworkRequest QueryNetworkRequest

func (x *QueryNetworkRequest) ProtoReflect() protoreflect.Message {
	return (*fastReflection_QueryNetworkRequest)(x)
}

func (x *QueryNetworkRequest) slowProtoReflect() protoreflect.Message {
	mi := &file_types_query_network_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_QueryNetworkRequest_messageType fastReflection_QueryNetworkRequest_messageType
var _ protoreflect.MessageType = fastReflection_QueryNetworkRequest_messageType{}

type fastReflection_QueryNetworkRequest_messageType struct{}

func (x fastReflection_QueryNetworkRequest_messageType) Zero() protoreflect.Message {
	return (*fastReflection_QueryNetworkRequest)(nil)
}
func (x fastReflection_QueryNetworkRequest_messageType) New() protoreflect.Message {
	return new(fastReflection_QueryNetworkRequest)
}
func (x fastReflection_QueryNetworkRequest_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_QueryNetworkRequest
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_QueryNetworkRequest) Descriptor() protoreflect.MessageDescriptor {
	return md_QueryNetworkRequest
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_QueryNetworkRequest) Type() protoreflect.MessageType {
	return _fastReflection_QueryNetworkRequest_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_QueryNetworkRequest) New() protoreflect.Message {
	return new(fastReflection_QueryNetworkRequest)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_QueryNetworkRequest) Interface() protoreflect.ProtoMessage {
	return (*QueryNetworkRequest)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_QueryNetworkRequest) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Height != "" {
		value := protoreflect.ValueOfString(x.Height)
		if !f(fd_QueryNetworkRequest_height, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_QueryNetworkRequest) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "types.QueryNetworkRequest.height":
		return x.Height != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: types.QueryNetworkRequest"))
		}
		panic(fmt.Errorf("message types.QueryNetworkRequest does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryNetworkRequest) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "types.QueryNetworkRequest.height":
		x.Height = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: types.QueryNetworkRequest"))
		}
		panic(fmt.Errorf("message types.QueryNetworkRequest does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_QueryNetworkRequest) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "types.QueryNetworkRequest.height":
		value := x.Height
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: types.QueryNetworkRequest"))
		}
		panic(fmt.Errorf("message types.QueryNetworkRequest does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryNetworkRequest) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "types.QueryNetworkRequest.height":
		x.Height = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: types.QueryNetworkRequest"))
		}
		panic(fmt.Errorf("message types.QueryNetworkRequest does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryNetworkRequest) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "types.QueryNetworkRequest.height":
		panic(fmt.Errorf("field height of message types.QueryNetworkRequest is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: types.QueryNetworkRequest"))
		}
		panic(fmt.Errorf("message types.QueryNetworkRequest does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_QueryNetworkRequest) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "types.QueryNetworkRequest.height":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: types.QueryNetworkRequest"))
		}
		panic(fmt.Errorf("message types.QueryNetworkRequest does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_QueryNetworkRequest) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in types.QueryNetworkRequest", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_QueryNetworkRequest) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryNetworkRequest) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_QueryNetworkRequest) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_QueryNetworkRequest) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*QueryNetworkRequest)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Height)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*QueryNetworkRequest)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Height) > 0 {
			i -= len(x.Height)
			copy(dAtA[i:], x.Height)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Height)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*QueryNetworkRequest)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: QueryNetworkRequest: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: QueryNetworkRequest: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Height = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var (
	md_QueryNetworkResponse                                   protoreflect.MessageDescriptor
	fd_QueryNetworkResponse_bond_reward_switch                protoreflect.FieldDescriptor
	fd_QueryNetworkResponse_total_bond_units                  protoreflect.FieldDescriptor
	fd_QueryNetworkResponse_available_pools_switch            protoreflect.FieldDescriptor
	fd_QueryNetworkResponse_vaults_liquidity_switch           protoreflect.FieldDescriptor
	fd_QueryNetworkResponse_effective_security_bond           protoreflect.FieldDescriptor
	fd_QueryNetworkResponse_total_reserve                     protoreflect.FieldDescriptor
	fd_QueryNetworkResponse_vaults_migrating                  protoreflect.FieldDescriptor
	fd_QueryNetworkResponse_gas_spent_switch                  protoreflect.FieldDescriptor
	fd_QueryNetworkResponse_gas_withheld_switch               protoreflect.FieldDescriptor
	fd_QueryNetworkResponse_outbound_fee_multiplier           protoreflect.FieldDescriptor
	fd_QueryNetworkResponse_native_outbound_fee_switch        protoreflect.FieldDescriptor
	fd_QueryNetworkResponse_native_tx_fee_switch              protoreflect.FieldDescriptor
	fd_QueryNetworkResponse_switchlyname_register_fee_switch  protoreflect.FieldDescriptor
	fd_QueryNetworkResponse_switchlyname_fee_per_block_switch protoreflect.FieldDescriptor
	fd_QueryNetworkResponse_switch_price_in_switchly          protoreflect.FieldDescriptor
	fd_QueryNetworkResponse_switchly_price_in_switch          protoreflect.FieldDescriptor
	fd_QueryNetworkResponse_switchly_price_halted             protoreflect.FieldDescriptor
)

func init() {
	file_types_query_network_proto_init()
	md_QueryNetworkResponse = File_types_query_network_proto.Messages().ByName("QueryNetworkResponse")
	fd_QueryNetworkResponse_bond_reward_switch = md_QueryNetworkResponse.Fields().ByName("bond_reward_switch")
	fd_QueryNetworkResponse_total_bond_units = md_QueryNetworkResponse.Fields().ByName("total_bond_units")
	fd_QueryNetworkResponse_available_pools_switch = md_QueryNetworkResponse.Fields().ByName("available_pools_switch")
	fd_QueryNetworkResponse_vaults_liquidity_switch = md_QueryNetworkResponse.Fields().ByName("vaults_liquidity_switch")
	fd_QueryNetworkResponse_effective_security_bond = md_QueryNetworkResponse.Fields().ByName("effective_security_bond")
	fd_QueryNetworkResponse_total_reserve = md_QueryNetworkResponse.Fields().ByName("total_reserve")
	fd_QueryNetworkResponse_vaults_migrating = md_QueryNetworkResponse.Fields().ByName("vaults_migrating")
	fd_QueryNetworkResponse_gas_spent_switch = md_QueryNetworkResponse.Fields().ByName("gas_spent_switch")
	fd_QueryNetworkResponse_gas_withheld_switch = md_QueryNetworkResponse.Fields().ByName("gas_withheld_switch")
	fd_QueryNetworkResponse_outbound_fee_multiplier = md_QueryNetworkResponse.Fields().ByName("outbound_fee_multiplier")
	fd_QueryNetworkResponse_native_outbound_fee_switch = md_QueryNetworkResponse.Fields().ByName("native_outbound_fee_switch")
	fd_QueryNetworkResponse_native_tx_fee_switch = md_QueryNetworkResponse.Fields().ByName("native_tx_fee_switch")
	fd_QueryNetworkResponse_switchlyname_register_fee_switch = md_QueryNetworkResponse.Fields().ByName("switchlyname_register_fee_switch")
	fd_QueryNetworkResponse_switchlyname_fee_per_block_switch = md_QueryNetworkResponse.Fields().ByName("switchlyname_fee_per_block_switch")
	fd_QueryNetworkResponse_switch_price_in_switchly = md_QueryNetworkResponse.Fields().ByName("switch_price_in_switchly")
	fd_QueryNetworkResponse_switchly_price_in_switch = md_QueryNetworkResponse.Fields().ByName("switchly_price_in_switch")
	fd_QueryNetworkResponse_switchly_price_halted = md_QueryNetworkResponse.Fields().ByName("switchly_price_halted")
}

var _ protoreflect.Message = (*fastReflection_QueryNetworkResponse)(nil)

type fastReflection_QueryNetworkResponse QueryNetworkResponse

func (x *QueryNetworkResponse) ProtoReflect() protoreflect.Message {
	return (*fastReflection_QueryNetworkResponse)(x)
}

func (x *QueryNetworkResponse) slowProtoReflect() protoreflect.Message {
	mi := &file_types_query_network_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_QueryNetworkResponse_messageType fastReflection_QueryNetworkResponse_messageType
var _ protoreflect.MessageType = fastReflection_QueryNetworkResponse_messageType{}

type fastReflection_QueryNetworkResponse_messageType struct{}

func (x fastReflection_QueryNetworkResponse_messageType) Zero() protoreflect.Message {
	return (*fastReflection_QueryNetworkResponse)(nil)
}
func (x fastReflection_QueryNetworkResponse_messageType) New() protoreflect.Message {
	return new(fastReflection_QueryNetworkResponse)
}
func (x fastReflection_QueryNetworkResponse_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_QueryNetworkResponse
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_QueryNetworkResponse) Descriptor() protoreflect.MessageDescriptor {
	return md_QueryNetworkResponse
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_QueryNetworkResponse) Type() protoreflect.MessageType {
	return _fastReflection_QueryNetworkResponse_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_QueryNetworkResponse) New() protoreflect.Message {
	return new(fastReflection_QueryNetworkResponse)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_QueryNetworkResponse) Interface() protoreflect.ProtoMessage {
	return (*QueryNetworkResponse)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_QueryNetworkResponse) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.BondRewardSwitch != "" {
		value := protoreflect.ValueOfString(x.BondRewardSwitch)
		if !f(fd_QueryNetworkResponse_bond_reward_switch, value) {
			return
		}
	}
	if x.TotalBondUnits != "" {
		value := protoreflect.ValueOfString(x.TotalBondUnits)
		if !f(fd_QueryNetworkResponse_total_bond_units, value) {
			return
		}
	}
	if x.AvailablePoolsSwitch != "" {
		value := protoreflect.ValueOfString(x.AvailablePoolsSwitch)
		if !f(fd_QueryNetworkResponse_available_pools_switch, value) {
			return
		}
	}
	if x.VaultsLiquiditySwitch != "" {
		value := protoreflect.ValueOfString(x.VaultsLiquiditySwitch)
		if !f(fd_QueryNetworkResponse_vaults_liquidity_switch, value) {
			return
		}
	}
	if x.EffectiveSecurityBond != "" {
		value := protoreflect.ValueOfString(x.EffectiveSecurityBond)
		if !f(fd_QueryNetworkResponse_effective_security_bond, value) {
			return
		}
	}
	if x.TotalReserve != "" {
		value := protoreflect.ValueOfString(x.TotalReserve)
		if !f(fd_QueryNetworkResponse_total_reserve, value) {
			return
		}
	}
	if x.VaultsMigrating != false {
		value := protoreflect.ValueOfBool(x.VaultsMigrating)
		if !f(fd_QueryNetworkResponse_vaults_migrating, value) {
			return
		}
	}
	if x.GasSpentSwitch != "" {
		value := protoreflect.ValueOfString(x.GasSpentSwitch)
		if !f(fd_QueryNetworkResponse_gas_spent_switch, value) {
			return
		}
	}
	if x.GasWithheldSwitch != "" {
		value := protoreflect.ValueOfString(x.GasWithheldSwitch)
		if !f(fd_QueryNetworkResponse_gas_withheld_switch, value) {
			return
		}
	}
	if x.OutboundFeeMultiplier != "" {
		value := protoreflect.ValueOfString(x.OutboundFeeMultiplier)
		if !f(fd_QueryNetworkResponse_outbound_fee_multiplier, value) {
			return
		}
	}
	if x.NativeOutboundFeeSwitch != "" {
		value := protoreflect.ValueOfString(x.NativeOutboundFeeSwitch)
		if !f(fd_QueryNetworkResponse_native_outbound_fee_switch, value) {
			return
		}
	}
	if x.NativeTxFeeSwitch != "" {
		value := protoreflect.ValueOfString(x.NativeTxFeeSwitch)
		if !f(fd_QueryNetworkResponse_native_tx_fee_switch, value) {
			return
		}
	}
	if x.SwitchlynameRegisterFeeSwitch != "" {
		value := protoreflect.ValueOfString(x.SwitchlynameRegisterFeeSwitch)
		if !f(fd_QueryNetworkResponse_switchlyname_register_fee_switch, value) {
			return
		}
	}
	if x.SwitchlynameFeePerBlockSwitch != "" {
		value := protoreflect.ValueOfString(x.SwitchlynameFeePerBlockSwitch)
		if !f(fd_QueryNetworkResponse_switchlyname_fee_per_block_switch, value) {
			return
		}
	}
	if x.SwitchPriceInSwitchly != "" {
		value := protoreflect.ValueOfString(x.SwitchPriceInSwitchly)
		if !f(fd_QueryNetworkResponse_switch_price_in_switchly, value) {
			return
		}
	}
	if x.SwitchlyPriceInSwitch != "" {
		value := protoreflect.ValueOfString(x.SwitchlyPriceInSwitch)
		if !f(fd_QueryNetworkResponse_switchly_price_in_switch, value) {
			return
		}
	}
	if x.SwitchlyPriceHalted != false {
		value := protoreflect.ValueOfBool(x.SwitchlyPriceHalted)
		if !f(fd_QueryNetworkResponse_switchly_price_halted, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_QueryNetworkResponse) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "types.QueryNetworkResponse.bond_reward_switch":
		return x.BondRewardSwitch != ""
	case "types.QueryNetworkResponse.total_bond_units":
		return x.TotalBondUnits != ""
	case "types.QueryNetworkResponse.available_pools_switch":
		return x.AvailablePoolsSwitch != ""
	case "types.QueryNetworkResponse.vaults_liquidity_switch":
		return x.VaultsLiquiditySwitch != ""
	case "types.QueryNetworkResponse.effective_security_bond":
		return x.EffectiveSecurityBond != ""
	case "types.QueryNetworkResponse.total_reserve":
		return x.TotalReserve != ""
	case "types.QueryNetworkResponse.vaults_migrating":
		return x.VaultsMigrating != false
	case "types.QueryNetworkResponse.gas_spent_switch":
		return x.GasSpentSwitch != ""
	case "types.QueryNetworkResponse.gas_withheld_switch":
		return x.GasWithheldSwitch != ""
	case "types.QueryNetworkResponse.outbound_fee_multiplier":
		return x.OutboundFeeMultiplier != ""
	case "types.QueryNetworkResponse.native_outbound_fee_switch":
		return x.NativeOutboundFeeSwitch != ""
	case "types.QueryNetworkResponse.native_tx_fee_switch":
		return x.NativeTxFeeSwitch != ""
	case "types.QueryNetworkResponse.switchlyname_register_fee_switch":
		return x.SwitchlynameRegisterFeeSwitch != ""
	case "types.QueryNetworkResponse.switchlyname_fee_per_block_switch":
		return x.SwitchlynameFeePerBlockSwitch != ""
	case "types.QueryNetworkResponse.switch_price_in_switchly":
		return x.SwitchPriceInSwitchly != ""
	case "types.QueryNetworkResponse.switchly_price_in_switch":
		return x.SwitchlyPriceInSwitch != ""
	case "types.QueryNetworkResponse.switchly_price_halted":
		return x.SwitchlyPriceHalted != false
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: types.QueryNetworkResponse"))
		}
		panic(fmt.Errorf("message types.QueryNetworkResponse does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryNetworkResponse) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "types.QueryNetworkResponse.bond_reward_switch":
		x.BondRewardSwitch = ""
	case "types.QueryNetworkResponse.total_bond_units":
		x.TotalBondUnits = ""
	case "types.QueryNetworkResponse.available_pools_switch":
		x.AvailablePoolsSwitch = ""
	case "types.QueryNetworkResponse.vaults_liquidity_switch":
		x.VaultsLiquiditySwitch = ""
	case "types.QueryNetworkResponse.effective_security_bond":
		x.EffectiveSecurityBond = ""
	case "types.QueryNetworkResponse.total_reserve":
		x.TotalReserve = ""
	case "types.QueryNetworkResponse.vaults_migrating":
		x.VaultsMigrating = false
	case "types.QueryNetworkResponse.gas_spent_switch":
		x.GasSpentSwitch = ""
	case "types.QueryNetworkResponse.gas_withheld_switch":
		x.GasWithheldSwitch = ""
	case "types.QueryNetworkResponse.outbound_fee_multiplier":
		x.OutboundFeeMultiplier = ""
	case "types.QueryNetworkResponse.native_outbound_fee_switch":
		x.NativeOutboundFeeSwitch = ""
	case "types.QueryNetworkResponse.native_tx_fee_switch":
		x.NativeTxFeeSwitch = ""
	case "types.QueryNetworkResponse.switchlyname_register_fee_switch":
		x.SwitchlynameRegisterFeeSwitch = ""
	case "types.QueryNetworkResponse.switchlyname_fee_per_block_switch":
		x.SwitchlynameFeePerBlockSwitch = ""
	case "types.QueryNetworkResponse.switch_price_in_switchly":
		x.SwitchPriceInSwitchly = ""
	case "types.QueryNetworkResponse.switchly_price_in_switch":
		x.SwitchlyPriceInSwitch = ""
	case "types.QueryNetworkResponse.switchly_price_halted":
		x.SwitchlyPriceHalted = false
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: types.QueryNetworkResponse"))
		}
		panic(fmt.Errorf("message types.QueryNetworkResponse does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_QueryNetworkResponse) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "types.QueryNetworkResponse.bond_reward_switch":
		value := x.BondRewardSwitch
		return protoreflect.ValueOfString(value)
	case "types.QueryNetworkResponse.total_bond_units":
		value := x.TotalBondUnits
		return protoreflect.ValueOfString(value)
	case "types.QueryNetworkResponse.available_pools_switch":
		value := x.AvailablePoolsSwitch
		return protoreflect.ValueOfString(value)
	case "types.QueryNetworkResponse.vaults_liquidity_switch":
		value := x.VaultsLiquiditySwitch
		return protoreflect.ValueOfString(value)
	case "types.QueryNetworkResponse.effective_security_bond":
		value := x.EffectiveSecurityBond
		return protoreflect.ValueOfString(value)
	case "types.QueryNetworkResponse.total_reserve":
		value := x.TotalReserve
		return protoreflect.ValueOfString(value)
	case "types.QueryNetworkResponse.vaults_migrating":
		value := x.VaultsMigrating
		return protoreflect.ValueOfBool(value)
	case "types.QueryNetworkResponse.gas_spent_switch":
		value := x.GasSpentSwitch
		return protoreflect.ValueOfString(value)
	case "types.QueryNetworkResponse.gas_withheld_switch":
		value := x.GasWithheldSwitch
		return protoreflect.ValueOfString(value)
	case "types.QueryNetworkResponse.outbound_fee_multiplier":
		value := x.OutboundFeeMultiplier
		return protoreflect.ValueOfString(value)
	case "types.QueryNetworkResponse.native_outbound_fee_switch":
		value := x.NativeOutboundFeeSwitch
		return protoreflect.ValueOfString(value)
	case "types.QueryNetworkResponse.native_tx_fee_switch":
		value := x.NativeTxFeeSwitch
		return protoreflect.ValueOfString(value)
	case "types.QueryNetworkResponse.switchlyname_register_fee_switch":
		value := x.SwitchlynameRegisterFeeSwitch
		return protoreflect.ValueOfString(value)
	case "types.QueryNetworkResponse.switchlyname_fee_per_block_switch":
		value := x.SwitchlynameFeePerBlockSwitch
		return protoreflect.ValueOfString(value)
	case "types.QueryNetworkResponse.switch_price_in_switchly":
		value := x.SwitchPriceInSwitchly
		return protoreflect.ValueOfString(value)
	case "types.QueryNetworkResponse.switchly_price_in_switch":
		value := x.SwitchlyPriceInSwitch
		return protoreflect.ValueOfString(value)
	case "types.QueryNetworkResponse.switchly_price_halted":
		value := x.SwitchlyPriceHalted
		return protoreflect.ValueOfBool(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: types.QueryNetworkResponse"))
		}
		panic(fmt.Errorf("message types.QueryNetworkResponse does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryNetworkResponse) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "types.QueryNetworkResponse.bond_reward_switch":
		x.BondRewardSwitch = value.Interface().(string)
	case "types.QueryNetworkResponse.total_bond_units":
		x.TotalBondUnits = value.Interface().(string)
	case "types.QueryNetworkResponse.available_pools_switch":
		x.AvailablePoolsSwitch = value.Interface().(string)
	case "types.QueryNetworkResponse.vaults_liquidity_switch":
		x.VaultsLiquiditySwitch = value.Interface().(string)
	case "types.QueryNetworkResponse.effective_security_bond":
		x.EffectiveSecurityBond = value.Interface().(string)
	case "types.QueryNetworkResponse.total_reserve":
		x.TotalReserve = value.Interface().(string)
	case "types.QueryNetworkResponse.vaults_migrating":
		x.VaultsMigrating = value.Bool()
	case "types.QueryNetworkResponse.gas_spent_switch":
		x.GasSpentSwitch = value.Interface().(string)
	case "types.QueryNetworkResponse.gas_withheld_switch":
		x.GasWithheldSwitch = value.Interface().(string)
	case "types.QueryNetworkResponse.outbound_fee_multiplier":
		x.OutboundFeeMultiplier = value.Interface().(string)
	case "types.QueryNetworkResponse.native_outbound_fee_switch":
		x.NativeOutboundFeeSwitch = value.Interface().(string)
	case "types.QueryNetworkResponse.native_tx_fee_switch":
		x.NativeTxFeeSwitch = value.Interface().(string)
	case "types.QueryNetworkResponse.switchlyname_register_fee_switch":
		x.SwitchlynameRegisterFeeSwitch = value.Interface().(string)
	case "types.QueryNetworkResponse.switchlyname_fee_per_block_switch":
		x.SwitchlynameFeePerBlockSwitch = value.Interface().(string)
	case "types.QueryNetworkResponse.switch_price_in_switchly":
		x.SwitchPriceInSwitchly = value.Interface().(string)
	case "types.QueryNetworkResponse.switchly_price_in_switch":
		x.SwitchlyPriceInSwitch = value.Interface().(string)
	case "types.QueryNetworkResponse.switchly_price_halted":
		x.SwitchlyPriceHalted = value.Bool()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: types.QueryNetworkResponse"))
		}
		panic(fmt.Errorf("message types.QueryNetworkResponse does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryNetworkResponse) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "types.QueryNetworkResponse.bond_reward_switch":
		panic(fmt.Errorf("field bond_reward_switch of message types.QueryNetworkResponse is not mutable"))
	case "types.QueryNetworkResponse.total_bond_units":
		panic(fmt.Errorf("field total_bond_units of message types.QueryNetworkResponse is not mutable"))
	case "types.QueryNetworkResponse.available_pools_switch":
		panic(fmt.Errorf("field available_pools_switch of message types.QueryNetworkResponse is not mutable"))
	case "types.QueryNetworkResponse.vaults_liquidity_switch":
		panic(fmt.Errorf("field vaults_liquidity_switch of message types.QueryNetworkResponse is not mutable"))
	case "types.QueryNetworkResponse.effective_security_bond":
		panic(fmt.Errorf("field effective_security_bond of message types.QueryNetworkResponse is not mutable"))
	case "types.QueryNetworkResponse.total_reserve":
		panic(fmt.Errorf("field total_reserve of message types.QueryNetworkResponse is not mutable"))
	case "types.QueryNetworkResponse.vaults_migrating":
		panic(fmt.Errorf("field vaults_migrating of message types.QueryNetworkResponse is not mutable"))
	case "types.QueryNetworkResponse.gas_spent_switch":
		panic(fmt.Errorf("field gas_spent_switch of message types.QueryNetworkResponse is not mutable"))
	case "types.QueryNetworkResponse.gas_withheld_switch":
		panic(fmt.Errorf("field gas_withheld_switch of message types.QueryNetworkResponse is not mutable"))
	case "types.QueryNetworkResponse.outbound_fee_multiplier":
		panic(fmt.Errorf("field outbound_fee_multiplier of message types.QueryNetworkResponse is not mutable"))
	case "types.QueryNetworkResponse.native_outbound_fee_switch":
		panic(fmt.Errorf("field native_outbound_fee_switch of message types.QueryNetworkResponse is not mutable"))
	case "types.QueryNetworkResponse.native_tx_fee_switch":
		panic(fmt.Errorf("field native_tx_fee_switch of message types.QueryNetworkResponse is not mutable"))
	case "types.QueryNetworkResponse.switchlyname_register_fee_switch":
		panic(fmt.Errorf("field switchlyname_register_fee_switch of message types.QueryNetworkResponse is not mutable"))
	case "types.QueryNetworkResponse.switchlyname_fee_per_block_switch":
		panic(fmt.Errorf("field switchlyname_fee_per_block_switch of message types.QueryNetworkResponse is not mutable"))
	case "types.QueryNetworkResponse.switch_price_in_switchly":
		panic(fmt.Errorf("field switch_price_in_switchly of message types.QueryNetworkResponse is not mutable"))
	case "types.QueryNetworkResponse.switchly_price_in_switch":
		panic(fmt.Errorf("field switchly_price_in_switch of message types.QueryNetworkResponse is not mutable"))
	case "types.QueryNetworkResponse.switchly_price_halted":
		panic(fmt.Errorf("field switchly_price_halted of message types.QueryNetworkResponse is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: types.QueryNetworkResponse"))
		}
		panic(fmt.Errorf("message types.QueryNetworkResponse does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_QueryNetworkResponse) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "types.QueryNetworkResponse.bond_reward_switch":
		return protoreflect.ValueOfString("")
	case "types.QueryNetworkResponse.total_bond_units":
		return protoreflect.ValueOfString("")
	case "types.QueryNetworkResponse.available_pools_switch":
		return protoreflect.ValueOfString("")
	case "types.QueryNetworkResponse.vaults_liquidity_switch":
		return protoreflect.ValueOfString("")
	case "types.QueryNetworkResponse.effective_security_bond":
		return protoreflect.ValueOfString("")
	case "types.QueryNetworkResponse.total_reserve":
		return protoreflect.ValueOfString("")
	case "types.QueryNetworkResponse.vaults_migrating":
		return protoreflect.ValueOfBool(false)
	case "types.QueryNetworkResponse.gas_spent_switch":
		return protoreflect.ValueOfString("")
	case "types.QueryNetworkResponse.gas_withheld_switch":
		return protoreflect.ValueOfString("")
	case "types.QueryNetworkResponse.outbound_fee_multiplier":
		return protoreflect.ValueOfString("")
	case "types.QueryNetworkResponse.native_outbound_fee_switch":
		return protoreflect.ValueOfString("")
	case "types.QueryNetworkResponse.native_tx_fee_switch":
		return protoreflect.ValueOfString("")
	case "types.QueryNetworkResponse.switchlyname_register_fee_switch":
		return protoreflect.ValueOfString("")
	case "types.QueryNetworkResponse.switchlyname_fee_per_block_switch":
		return protoreflect.ValueOfString("")
	case "types.QueryNetworkResponse.switch_price_in_switchly":
		return protoreflect.ValueOfString("")
	case "types.QueryNetworkResponse.switchly_price_in_switch":
		return protoreflect.ValueOfString("")
	case "types.QueryNetworkResponse.switchly_price_halted":
		return protoreflect.ValueOfBool(false)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: types.QueryNetworkResponse"))
		}
		panic(fmt.Errorf("message types.QueryNetworkResponse does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_QueryNetworkResponse) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in types.QueryNetworkResponse", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_QueryNetworkResponse) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryNetworkResponse) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_QueryNetworkResponse) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_QueryNetworkResponse) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*QueryNetworkResponse)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.BondRewardSwitch)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.TotalBondUnits)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.AvailablePoolsSwitch)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.VaultsLiquiditySwitch)
		if l > 0 {
			n += 2 + l + runtime.Sov(uint64(l))
		}
		l = len(x.EffectiveSecurityBond)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.TotalReserve)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.VaultsMigrating {
			n += 2
		}
		l = len(x.GasSpentSwitch)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.GasWithheldSwitch)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.OutboundFeeMultiplier)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.NativeOutboundFeeSwitch)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.NativeTxFeeSwitch)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.SwitchlynameRegisterFeeSwitch)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.SwitchlynameFeePerBlockSwitch)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.SwitchPriceInSwitchly)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.SwitchlyPriceInSwitch)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.SwitchlyPriceHalted {
			n += 3
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*QueryNetworkResponse)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.SwitchlyPriceHalted {
			i--
			if x.SwitchlyPriceHalted {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x88
		}
		if len(x.VaultsLiquiditySwitch) > 0 {
			i -= len(x.VaultsLiquiditySwitch)
			copy(dAtA[i:], x.VaultsLiquiditySwitch)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.VaultsLiquiditySwitch)))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x82
		}
		if len(x.AvailablePoolsSwitch) > 0 {
			i -= len(x.AvailablePoolsSwitch)
			copy(dAtA[i:], x.AvailablePoolsSwitch)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.AvailablePoolsSwitch)))
			i--
			dAtA[i] = 0x7a
		}
		if len(x.SwitchlyPriceInSwitch) > 0 {
			i -= len(x.SwitchlyPriceInSwitch)
			copy(dAtA[i:], x.SwitchlyPriceInSwitch)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.SwitchlyPriceInSwitch)))
			i--
			dAtA[i] = 0x72
		}
		if len(x.SwitchPriceInSwitchly) > 0 {
			i -= len(x.SwitchPriceInSwitchly)
			copy(dAtA[i:], x.SwitchPriceInSwitchly)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.SwitchPriceInSwitchly)))
			i--
			dAtA[i] = 0x6a
		}
		if len(x.SwitchlynameFeePerBlockSwitch) > 0 {
			i -= len(x.SwitchlynameFeePerBlockSwitch)
			copy(dAtA[i:], x.SwitchlynameFeePerBlockSwitch)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.SwitchlynameFeePerBlockSwitch)))
			i--
			dAtA[i] = 0x62
		}
		if len(x.SwitchlynameRegisterFeeSwitch) > 0 {
			i -= len(x.SwitchlynameRegisterFeeSwitch)
			copy(dAtA[i:], x.SwitchlynameRegisterFeeSwitch)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.SwitchlynameRegisterFeeSwitch)))
			i--
			dAtA[i] = 0x5a
		}
		if len(x.NativeTxFeeSwitch) > 0 {
			i -= len(x.NativeTxFeeSwitch)
			copy(dAtA[i:], x.NativeTxFeeSwitch)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.NativeTxFeeSwitch)))
			i--
			dAtA[i] = 0x52
		}
		if len(x.NativeOutboundFeeSwitch) > 0 {
			i -= len(x.NativeOutboundFeeSwitch)
			copy(dAtA[i:], x.NativeOutboundFeeSwitch)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.NativeOutboundFeeSwitch)))
			i--
			dAtA[i] = 0x4a
		}
		if len(x.OutboundFeeMultiplier) > 0 {
			i -= len(x.OutboundFeeMultiplier)
			copy(dAtA[i:], x.OutboundFeeMultiplier)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.OutboundFeeMultiplier)))
			i--
			dAtA[i] = 0x42
		}
		if len(x.GasWithheldSwitch) > 0 {
			i -= len(x.GasWithheldSwitch)
			copy(dAtA[i:], x.GasWithheldSwitch)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.GasWithheldSwitch)))
			i--
			dAtA[i] = 0x3a
		}
		if len(x.GasSpentSwitch) > 0 {
			i -= len(x.GasSpentSwitch)
			copy(dAtA[i:], x.GasSpentSwitch)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.GasSpentSwitch)))
			i--
			dAtA[i] = 0x32
		}
		if x.VaultsMigrating {
			i--
			if x.VaultsMigrating {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x28
		}
		if len(x.TotalReserve) > 0 {
			i -= len(x.TotalReserve)
			copy(dAtA[i:], x.TotalReserve)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.TotalReserve)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.EffectiveSecurityBond) > 0 {
			i -= len(x.EffectiveSecurityBond)
			copy(dAtA[i:], x.EffectiveSecurityBond)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.EffectiveSecurityBond)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.TotalBondUnits) > 0 {
			i -= len(x.TotalBondUnits)
			copy(dAtA[i:], x.TotalBondUnits)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.TotalBondUnits)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.BondRewardSwitch) > 0 {
			i -= len(x.BondRewardSwitch)
			copy(dAtA[i:], x.BondRewardSwitch)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.BondRewardSwitch)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*QueryNetworkResponse)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: QueryNetworkResponse: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: QueryNetworkResponse: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field BondRewardSwitch", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.BondRewardSwitch = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TotalBondUnits", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.TotalBondUnits = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 15:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field AvailablePoolsSwitch", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.AvailablePoolsSwitch = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 16:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field VaultsLiquiditySwitch", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.VaultsLiquiditySwitch = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field EffectiveSecurityBond", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.EffectiveSecurityBond = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TotalReserve", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.TotalReserve = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field VaultsMigrating", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.VaultsMigrating = bool(v != 0)
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field GasSpentSwitch", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.GasSpentSwitch = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 7:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field GasWithheldSwitch", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.GasWithheldSwitch = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 8:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field OutboundFeeMultiplier", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.OutboundFeeMultiplier = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 9:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field NativeOutboundFeeSwitch", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.NativeOutboundFeeSwitch = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 10:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field NativeTxFeeSwitch", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.NativeTxFeeSwitch = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 11:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SwitchlynameRegisterFeeSwitch", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.SwitchlynameRegisterFeeSwitch = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 12:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SwitchlynameFeePerBlockSwitch", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.SwitchlynameFeePerBlockSwitch = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 13:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SwitchPriceInSwitchly", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.SwitchPriceInSwitchly = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 14:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SwitchlyPriceInSwitch", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.SwitchlyPriceInSwitch = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 17:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SwitchlyPriceHalted", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.SwitchlyPriceHalted = bool(v != 0)
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: types/query_network.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryNetworkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height string `protobuf:"bytes,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *QueryNetworkRequest) Reset() {
	*x = QueryNetworkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_query_network_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNetworkRequest) ProtoMessage() {}

// Deprecated: Use QueryNetworkRequest.ProtoReflect.Descriptor instead.
func (*QueryNetworkRequest) Descriptor() ([]byte, []int) {
	return file_types_query_network_proto_rawDescGZIP(), []int{0}
}

func (x *QueryNetworkRequest) GetHeight() string {
	if x != nil {
		return x.Height
	}
	return ""
}

type QueryNetworkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// total amount of SWITCH awarded to node operators
	BondRewardSwitch string `protobuf:"bytes,1,opt,name=bond_reward_switch,json=bondRewardSwitch,proto3" json:"bond_reward_switch,omitempty"`
	// total bonded SWITCH
	TotalBondUnits string `protobuf:"bytes,2,opt,name=total_bond_units,json=totalBondUnits,proto3" json:"total_bond_units,omitempty"`
	// SWITCH in Available pools (equal in value to the Assets in those pools)
	AvailablePoolsSwitch string `protobuf:"bytes,15,opt,name=available_pools_switch,json=availablePoolsSwitch,proto3" json:"available_pools_switch,omitempty"`
	// SWITCH value of Layer 1 Assets in vaults
	VaultsLiquiditySwitch string `protobuf:"bytes,16,opt,name=vaults_liquidity_switch,json=vaultsLiquiditySwitch,proto3" json:"vaults_liquidity_switch,omitempty"`
	// effective security bond used to determine maximum pooled SWITCH
	EffectiveSecurityBond string `protobuf:"bytes,3,opt,name=effective_security_bond,json=effectiveSecurityBond,proto3" json:"effective_security_bond,omitempty"`
	// total reserve SWITCH
	TotalReserve string `protobuf:"bytes,4,opt,name=total_reserve,json=totalReserve,proto3" json:"total_reserve,omitempty"`
	// Returns true if there exist RetiringVaults which have not finished migrating funds to new ActiveVaults
	VaultsMigrating bool `protobuf:"varint,5,opt,name=vaults_migrating,json=vaultsMigrating,proto3" json:"vaults_migrating,omitempty"`
	// Sum of the gas the network has spent to send outbounds
	GasSpentSwitch string `protobuf:"bytes,6,opt,name=gas_spent_switch,json=gasSpentSwitch,proto3" json:"gas_spent_switch,omitempty"`
	// Sum of the gas withheld from users to cover outbound gas
	GasWithheldSwitch string `protobuf:"bytes,7,opt,name=gas_withheld_switch,json=gasWithheldSwitch,proto3" json:"gas_withheld_switch,omitempty"`
	// Current outbound fee multiplier, in basis points
	OutboundFeeMultiplier string `protobuf:"bytes,8,opt,name=outbound_fee_multiplier,json=outboundFeeMultiplier,proto3" json:"outbound_fee_multiplier,omitempty"`
	// the outbound transaction fee in switch, converted from the NativeOutboundFeeUSD mimir (after USD fees are enabled)
	NativeOutboundFeeSwitch string `protobuf:"bytes,9,opt,name=native_outbound_fee_switch,json=nativeOutboundFeeSwitch,proto3" json:"native_outbound_fee_switch,omitempty"`
	// the native transaction fee in switch, converted from the NativeTransactionFeeUSD mimir (after USD fees are enabled)
	NativeTxFeeSwitch string `protobuf:"bytes,10,opt,name=native_tx_fee_switch,json=nativeTxFeeSwitch,proto3" json:"native_tx_fee_switch,omitempty"`
	// the switchlyname register fee in switch, converted from the TNSRegisterFeeUSD mimir (after USD fees are enabled)
	SwitchlynameRegisterFeeSwitch string `protobuf:"bytes,11,opt,name=switchlyname_register_fee_switch,json=switchlynameRegisterFeeSwitch,proto3" json:"switchlyname_register_fee_switch,omitempty"`
	// the switchlyname fee per block in switch, converted from the TNSFeePerBlockUSD mimir (after USD fees are enabled)
	SwitchlynameFeePerBlockSwitch string `protobuf:"bytes,12,opt,name=switchlyname_fee_per_block_switch,json=switchlynameFeePerBlockSwitch,proto3" json:"switchlyname_fee_per_block_switch,omitempty"`
	// the switch price in switchly
	SwitchPriceInSwitchly string `protobuf:"bytes,13,opt,name=switch_price_in_switchly,json=switchPriceInSwitchly,proto3" json:"switch_price_in_switchly,omitempty"`
	// the switchly price in switch
	SwitchlyPriceInSwitch string `protobuf:"bytes,14,opt,name=switchly_price_in_switch,json=switchlyPriceInSwitch,proto3" json:"switchly_price_in_switch,omitempty"`
	// indicator if all anchor chains are halted
	SwitchlyPriceHalted bool `protobuf:"varint,17,opt,name=switchly_price_halted,json=switchlyPriceHalted,proto3" json:"switchly_price_halted,omitempty"`
}

func (x *QueryNetworkResponse) Reset() {
	*x = QueryNetworkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_query_network_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNetworkResponse) ProtoMessage() {}

// Deprecated: Use QueryNetworkResponse.ProtoReflect.Descriptor instead.
func (*QueryNetworkResponse) Descriptor() ([]byte, []int) {
	return file_types_query_network_proto_rawDescGZIP(), []int{1}
}

func (x *QueryNetworkResponse) GetBondRewardSwitch() string {
	if x != nil {
		return x.BondRewardSwitch
	}
	return ""
}

func (x *QueryNetworkResponse) GetTotalBondUnits() string {
	if x != nil {
		return x.TotalBondUnits
	}
	return ""
}

func (x *QueryNetworkResponse) GetAvailablePoolsSwitch() string {
	if x != nil {
		return x.AvailablePoolsSwitch
	}
	return ""
}

func (x *QueryNetworkResponse) GetVaultsLiquiditySwitch() string {
	if x != nil {
		return x.VaultsLiquiditySwitch
	}
	return ""
}

func (x *QueryNetworkResponse) GetEffectiveSecurityBond() string {
	if x != nil {
		return x.EffectiveSecurityBond
	}
	return ""
}

func (x *QueryNetworkResponse) GetTotalReserve() string {
	if x != nil {
		return x.TotalReserve
	}
	return ""
}

func (x *QueryNetworkResponse) GetVaultsMigrating() bool {
	if x != nil {
		return x.VaultsMigrating
	}
	return false
}

func (x *QueryNetworkResponse) GetGasSpentSwitch() string {
	if x != nil {
		return x.GasSpentSwitch
	}
	return ""
}

func (x *QueryNetworkResponse) GetGasWithheldSwitch() string {
	if x != nil {
		return x.GasWithheldSwitch
	}
	return ""
}

func (x *QueryNetworkResponse) GetOutboundFeeMultiplier() string {
	if x != nil {
		return x.OutboundFeeMultiplier
	}
	return ""
}

func (x *QueryNetworkResponse) GetNativeOutboundFeeSwitch() string {
	if x != nil {
		return x.NativeOutboundFeeSwitch
	}
	return ""
}

func (x *QueryNetworkResponse) GetNativeTxFeeSwitch() string {
	if x != nil {
		return x.NativeTxFeeSwitch
	}
	return ""
}

func (x *QueryNetworkResponse) GetSwitchlynameRegisterFeeSwitch() string {
	if x != nil {
		return x.SwitchlynameRegisterFeeSwitch
	}
	return ""
}

func (x *QueryNetworkResponse) GetSwitchlynameFeePerBlockSwitch() string {
	if x != nil {
		return x.SwitchlynameFeePerBlockSwitch
	}
	return ""
}

func (x *QueryNetworkResponse) GetSwitchPriceInSwitchly() string {
	if x != nil {
		return x.SwitchPriceInSwitchly
	}
	return ""
}

func (x *QueryNetworkResponse) GetSwitchlyPriceInSwitch() string {
	if x != nil {
		return x.SwitchlyPriceInSwitch
	}
	return ""
}

func (x *QueryNetworkResponse) GetSwitchlyPriceHalted() bool {
	if x != nil {
		return x.SwitchlyPriceHalted
	}
	return false
}

var File_types_query_network_proto protoreflect.FileDescriptor

var file_types_query_network_proto_rawDesc = []byte{
	0x0a, 0x19, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f,
	0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x13, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0xd7, 0x0a, 0x0a, 0x14, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x44, 0x0a, 0x12, 0x62, 0x6f, 0x6e, 0x64, 0x5f, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f,
	0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x16, 0xea, 0xde,
	0x1f, 0x12, 0x62, 0x6f, 0x6e, 0x64, 0x5f, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x73, 0x77,
	0x69, 0x74, 0x63, 0x68, 0x52, 0x10, 0x62, 0x6f, 0x6e, 0x64, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x12, 0x3e, 0x0a, 0x10, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f,
	0x62, 0x6f, 0x6e, 0x64, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x14, 0xea, 0xde, 0x1f, 0x10, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x62, 0x6f, 0x6e, 0x64,
	0x5f, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x52, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x6f, 0x6e,
	0x64, 0x55, 0x6e, 0x69, 0x74, 0x73, 0x12, 0x50, 0x0a, 0x16, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x5f, 0x70, 0x6f, 0x6f, 0x6c, 0x73, 0x5f, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68,
	0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x42, 0x1a, 0xea, 0xde, 0x1f, 0x16, 0x61, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x70, 0x6f, 0x6f, 0x6c, 0x73, 0x5f, 0x73, 0x77, 0x69, 0x74,
	0x63, 0x68, 0x52, 0x14, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x6f, 0x6f,
	0x6c, 0x73, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x12, 0x53, 0x0a, 0x17, 0x76, 0x61, 0x75, 0x6c,
	0x74, 0x73, 0x5f, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x69, 0x74, 0x79, 0x5f, 0x73, 0x77, 0x69,
	0x74, 0x63, 0x68, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x42, 0x1b, 0xea, 0xde, 0x1f, 0x17, 0x76,
	0x61, 0x75, 0x6c, 0x74, 0x73, 0x5f, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x69, 0x74, 0x79, 0x5f,
	0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x52, 0x15, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x4c, 0x69,
	0x71, 0x75, 0x69, 0x64, 0x69, 0x74, 0x79, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x12, 0x53, 0x0a,
	0x17, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x75, 0x72,
	0x69, 0x74, 0x79, 0x5f, 0x62, 0x6f, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x1b,
	0xea, 0xde, 0x1f, 0x17, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x73, 0x65,
	0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x62, 0x6f, 0x6e, 0x64, 0x52, 0x15, 0x65, 0x66, 0x66,
	0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x42, 0x6f,
	0x6e, 0x64, 0x12, 0x36, 0x0a, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x72, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x11, 0xea, 0xde, 0x1f, 0x0d, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x52, 0x0c, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x12, 0x3f, 0x0a, 0x10, 0x76, 0x61,
	0x75, 0x6c, 0x74, 0x73, 0x5f, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x42, 0x14, 0xea, 0xde, 0x1f, 0x10, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x73,
	0x5f, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x0f, 0x76, 0x61, 0x75, 0x6c,
	0x74, 0x73, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x3e, 0x0a, 0x10, 0x67,
	0x61, 0x73, 0x5f, 0x73, 0x70, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x42, 0x14, 0xea, 0xde, 0x1f, 0x10, 0x67, 0x61, 0x73, 0x5f, 0x73,
	0x70, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x52, 0x0e, 0x67, 0x61, 0x73,
	0x53, 0x70, 0x65, 0x6e, 0x74, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x12, 0x47, 0x0a, 0x13, 0x67,
	0x61, 0x73, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x68, 0x65, 0x6c, 0x64, 0x5f, 0x73, 0x77, 0x69, 0x74,
	0x63, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x42, 0x17, 0xea, 0xde, 0x1f, 0x13, 0x67, 0x61,
	0x73, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x68, 0x65, 0x6c, 0x64, 0x5f, 0x73, 0x77, 0x69, 0x74, 0x63,
	0x68, 0x52, 0x11, 0x67, 0x61, 0x73, 0x57, 0x69, 0x74, 0x68, 0x68, 0x65, 0x6c, 0x64, 0x53, 0x77,
	0x69, 0x74, 0x63, 0x68, 0x12, 0x36, 0x0a, 0x17, 0x6f, 0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64,
	0x5f, 0x66, 0x65, 0x65, 0x5f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x6f, 0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x46,
	0x65, 0x65, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x12, 0x5b, 0x0a, 0x1a,
	0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x6f, 0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x5f,
	0x66, 0x65, 0x65, 0x5f, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x1e, 0xea, 0xde, 0x1f, 0x1a, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x6f, 0x75, 0x74,
	0x62, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x66, 0x65, 0x65, 0x5f, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68,
	0x52, 0x17, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x4f, 0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64,
	0x46, 0x65, 0x65, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x12, 0x49, 0x0a, 0x14, 0x6e, 0x61, 0x74,
	0x69, 0x76, 0x65, 0x5f, 0x74, 0x78, 0x5f, 0x66, 0x65, 0x65, 0x5f, 0x73, 0x77, 0x69, 0x74, 0x63,
	0x68, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x42, 0x18, 0xea, 0xde, 0x1f, 0x14, 0x6e, 0x61, 0x74,
	0x69, 0x76, 0x65, 0x5f, 0x74, 0x78, 0x5f, 0x66, 0x65, 0x65, 0x5f, 0x73, 0x77, 0x69, 0x74, 0x63,
	0x68, 0x52, 0x11, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x54, 0x78, 0x46, 0x65, 0x65, 0x53, 0x77,
	0x69, 0x74, 0x63, 0x68, 0x12, 0x6d, 0x0a, 0x20, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x6c, 0x79,
	0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x66, 0x65,
	0x65, 0x5f, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x42, 0x24,
	0xea, 0xde, 0x1f, 0x20, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x6c, 0x79, 0x6e, 0x61, 0x6d, 0x65,
	0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x66, 0x65, 0x65, 0x5f, 0x73, 0x77,
	0x69, 0x74, 0x63, 0x68, 0x52, 0x1d, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x6c, 0x79, 0x6e, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x46, 0x65, 0x65, 0x53, 0x77, 0x69,
	0x74, 0x63, 0x68, 0x12, 0x6f, 0x0a, 0x21, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x6c, 0x79, 0x6e,
	0x61, 0x6d, 0x65, 0x5f, 0x66, 0x65, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x5f, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x42, 0x25,
	0xea, 0xde, 0x1f, 0x21, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x6c, 0x79, 0x6e, 0x61, 0x6d, 0x65,
	0x5f, 0x66, 0x65, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x73,
	0x77, 0x69, 0x74, 0x63, 0x68, 0x52, 0x1d, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x6c, 0x79, 0x6e,
	0x61, 0x6d, 0x65, 0x46, 0x65, 0x65, 0x50, 0x65, 0x72, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x77,
	0x69, 0x74, 0x63, 0x68, 0x12, 0x55, 0x0a, 0x18, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x5f, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x6e, 0x5f, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x6c, 0x79,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x42, 0x1c, 0xea, 0xde, 0x1f, 0x18, 0x73, 0x77, 0x69, 0x74,
	0x63, 0x68, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x6e, 0x5f, 0x73, 0x77, 0x69, 0x74,
	0x63, 0x68, 0x6c, 0x79, 0x52, 0x15, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x49, 0x6e, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x6c, 0x79, 0x12, 0x55, 0x0a, 0x18, 0x73,
	0x77, 0x69, 0x74, 0x63, 0x68, 0x6c, 0x79, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x6e,
	0x5f, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x42, 0x1c, 0xea,
	0xde, 0x1f, 0x18, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x6c, 0x79, 0x5f, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x5f, 0x69, 0x6e, 0x5f, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x52, 0x15, 0x73, 0x77, 0x69,
	0x74, 0x63, 0x68, 0x6c, 0x79, 0x50, 0x72, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x53, 0x77, 0x69, 0x74,
	0x63, 0x68, 0x12, 0x4d, 0x0a, 0x15, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x6c, 0x79, 0x5f, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x5f, 0x68, 0x61, 0x6c, 0x74, 0x65, 0x64, 0x18, 0x11, 0x20, 0x01, 0x28,
	0x08, 0x42, 0x19, 0xea, 0xde, 0x1f, 0x15, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x6c, 0x79, 0x5f,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x68, 0x61, 0x6c, 0x74, 0x65, 0x64, 0x52, 0x13, 0x73, 0x77,
	0x69, 0x74, 0x63, 0x68, 0x6c, 0x79, 0x50, 0x72, 0x69, 0x63, 0x65, 0x48, 0x61, 0x6c, 0x74, 0x65,
	0x64, 0x42, 0x8d, 0x01, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x42,
	0x11, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x6c, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2f, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x6c, 0x79, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x76,
	0x33, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0xa2, 0x02, 0x03, 0x54, 0x58,
	0x58, 0xaa, 0x02, 0x05, 0x54, 0x79, 0x70, 0x65, 0x73, 0xca, 0x02, 0x05, 0x54, 0x79, 0x70, 0x65,
	0x73, 0xe2, 0x02, 0x11, 0x54, 0x79, 0x70, 0x65, 0x73, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x05, 0x54, 0x79, 0x70, 0x65, 0x73, 0xc8, 0xe2, 0x1e,
	0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_types_query_network_proto_rawDescOnce sync.Once
	file_types_query_network_proto_rawDescData = file_types_query_network_proto_rawDesc
)

func file_types_query_network_proto_rawDescGZIP() []byte {
	file_types_query_network_proto_rawDescOnce.Do(func() {
		file_types_query_network_proto_rawDescData = protoimpl.X.CompressGZIP(file_types_query_network_proto_rawDescData)
	})
	return file_types_query_network_proto_rawDescData
}

var file_types_query_network_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_types_query_network_proto_goTypes = []interface{}{
	(*QueryNetworkRequest)(nil),  // 0: types.QueryNetworkRequest
	(*QueryNetworkResponse)(nil), // 1: types.QueryNetworkResponse
}
var file_types_query_network_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_types_query_network_proto_init() }
func file_types_query_network_proto_init() {
	if File_types_query_network_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_types_query_network_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryNetworkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_query_network_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryNetworkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_types_query_network_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_query_network_proto_goTypes,
		DependencyIndexes: file_types_query_network_proto_depIdxs,
		MessageInfos:      file_types_query_network_proto_msgTypes,
	}.Build()
	File_types_query_network_proto = out.File
	file_types_query_network_proto_rawDesc = nil
	file_types_query_network_proto_goTypes = nil
	file_types_query_network_proto_depIdxs = nil
}
