// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types/query_outbound_fee.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryOutboundFeeRequest struct {
	Asset  string `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	Height string `protobuf:"bytes,2,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *QueryOutboundFeeRequest) Reset()         { *m = QueryOutboundFeeRequest{} }
func (m *QueryOutboundFeeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryOutboundFeeRequest) ProtoMessage()    {}
func (*QueryOutboundFeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec7cb76bf82f4d2e, []int{0}
}
func (m *QueryOutboundFeeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryOutboundFeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryOutboundFeeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryOutboundFeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOutboundFeeRequest.Merge(m, src)
}
func (m *QueryOutboundFeeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryOutboundFeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOutboundFeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOutboundFeeRequest proto.InternalMessageInfo

func (m *QueryOutboundFeeRequest) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *QueryOutboundFeeRequest) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

type QueryOutboundFeeResponse struct {
	// the asset to display the outbound fee for
	Asset string `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset"`
	// the asset's outbound fee, in (1e8-format) units of the asset
	OutboundFee string `protobuf:"bytes,2,opt,name=outbound_fee,json=outboundFee,proto3" json:"outbound_fee"`
	// Total SWITCH the network has withheld as fees to later cover gas costs for this asset's outbounds
	FeeWithheldSwitch string `protobuf:"bytes,3,opt,name=fee_withheld_switch,json=feeWithheldSwitch,proto3" json:"fee_withheld_switch,omitempty"`
	// Total SWITCH the network has spent to reimburse gas costs for this asset's outbounds
	FeeSpentSwitch string `protobuf:"bytes,4,opt,name=fee_spent_switch,json=feeSpentSwitch,proto3" json:"fee_spent_switch,omitempty"`
	// amount of SWITCH by which the fee_withheld_switch exceeds the fee_spent_switch
	SurplusSwitch string `protobuf:"bytes,5,opt,name=surplus_switch,json=surplusSwitch,proto3" json:"surplus_switch,omitempty"`
	// dynamic multiplier basis points, based on the surplus_switch, affecting the size of the outbound_fee
	DynamicMultiplierBasisPoints string `protobuf:"bytes,6,opt,name=dynamic_multiplier_basis_points,json=dynamicMultiplierBasisPoints,proto3" json:"dynamic_multiplier_basis_points,omitempty"`
}

func (m *QueryOutboundFeeResponse) Reset()         { *m = QueryOutboundFeeResponse{} }
func (m *QueryOutboundFeeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryOutboundFeeResponse) ProtoMessage()    {}
func (*QueryOutboundFeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec7cb76bf82f4d2e, []int{1}
}
func (m *QueryOutboundFeeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryOutboundFeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryOutboundFeeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryOutboundFeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOutboundFeeResponse.Merge(m, src)
}
func (m *QueryOutboundFeeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryOutboundFeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOutboundFeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOutboundFeeResponse proto.InternalMessageInfo

func (m *QueryOutboundFeeResponse) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *QueryOutboundFeeResponse) GetOutboundFee() string {
	if m != nil {
		return m.OutboundFee
	}
	return ""
}

func (m *QueryOutboundFeeResponse) GetFeeWithheldSwitch() string {
	if m != nil {
		return m.FeeWithheldSwitch
	}
	return ""
}

func (m *QueryOutboundFeeResponse) GetFeeSpentSwitch() string {
	if m != nil {
		return m.FeeSpentSwitch
	}
	return ""
}

func (m *QueryOutboundFeeResponse) GetSurplusSwitch() string {
	if m != nil {
		return m.SurplusSwitch
	}
	return ""
}

func (m *QueryOutboundFeeResponse) GetDynamicMultiplierBasisPoints() string {
	if m != nil {
		return m.DynamicMultiplierBasisPoints
	}
	return ""
}

type QueryOutboundFeesRequest struct {
	Height string `protobuf:"bytes,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *QueryOutboundFeesRequest) Reset()         { *m = QueryOutboundFeesRequest{} }
func (m *QueryOutboundFeesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryOutboundFeesRequest) ProtoMessage()    {}
func (*QueryOutboundFeesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec7cb76bf82f4d2e, []int{2}
}
func (m *QueryOutboundFeesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryOutboundFeesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryOutboundFeesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryOutboundFeesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOutboundFeesRequest.Merge(m, src)
}
func (m *QueryOutboundFeesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryOutboundFeesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOutboundFeesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOutboundFeesRequest proto.InternalMessageInfo

func (m *QueryOutboundFeesRequest) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

type QueryOutboundFeesResponse struct {
	OutboundFees []*QueryOutboundFeeResponse `protobuf:"bytes,1,rep,name=outbound_fees,json=outboundFees,proto3" json:"outbound_fees,omitempty"`
}

func (m *QueryOutboundFeesResponse) Reset()         { *m = QueryOutboundFeesResponse{} }
func (m *QueryOutboundFeesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryOutboundFeesResponse) ProtoMessage()    {}
func (*QueryOutboundFeesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec7cb76bf82f4d2e, []int{3}
}
func (m *QueryOutboundFeesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryOutboundFeesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryOutboundFeesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryOutboundFeesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOutboundFeesResponse.Merge(m, src)
}
func (m *QueryOutboundFeesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryOutboundFeesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOutboundFeesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOutboundFeesResponse proto.InternalMessageInfo

func (m *QueryOutboundFeesResponse) GetOutboundFees() []*QueryOutboundFeeResponse {
	if m != nil {
		return m.OutboundFees
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryOutboundFeeRequest)(nil), "types.QueryOutboundFeeRequest")
	proto.RegisterType((*QueryOutboundFeeResponse)(nil), "types.QueryOutboundFeeResponse")
	proto.RegisterType((*QueryOutboundFeesRequest)(nil), "types.QueryOutboundFeesRequest")
	proto.RegisterType((*QueryOutboundFeesResponse)(nil), "types.QueryOutboundFeesResponse")
}

func init() { proto.RegisterFile("types/query_outbound_fee.proto", fileDescriptor_ec7cb76bf82f4d2e) }

var fileDescriptor_ec7cb76bf82f4d2e = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcd, 0xaa, 0xd3, 0x40,
	0x18, 0x86, 0x9b, 0x73, 0x6c, 0xe1, 0xcc, 0xf9, 0xe1, 0x18, 0x0f, 0x1a, 0x45, 0x92, 0x43, 0x41,
	0xe8, 0x2a, 0x81, 0x76, 0xeb, 0x2a, 0xf8, 0xb3, 0x12, 0x35, 0x05, 0x05, 0x37, 0x21, 0x3f, 0x5f,
	0x92, 0x81, 0x34, 0x93, 0xe6, 0x9b, 0xb1, 0xe6, 0x2e, 0xbc, 0x1c, 0x2f, 0xc1, 0x65, 0x97, 0xae,
	0x8a, 0xb4, 0xbb, 0x5e, 0x85, 0x64, 0x32, 0xe9, 0x0f, 0xf5, 0xec, 0x32, 0xef, 0xf7, 0xbc, 0x6f,
	0x86, 0x77, 0x3e, 0x62, 0xf2, 0xba, 0x04, 0x74, 0xe6, 0x02, 0xaa, 0xda, 0x67, 0x82, 0x87, 0x4c,
	0x14, 0xb1, 0x9f, 0x00, 0xd8, 0x65, 0xc5, 0x38, 0xd3, 0xfb, 0x72, 0xfe, 0xe2, 0x2e, 0x65, 0x29,
	0x93, 0x8a, 0xd3, 0x7c, 0xb5, 0xc3, 0xe1, 0x7b, 0xf2, 0xec, 0x73, 0x63, 0xfc, 0xa8, 0x7c, 0xef,
	0x00, 0x3c, 0x98, 0x0b, 0x40, 0xae, 0xdf, 0x91, 0x7e, 0x80, 0x08, 0xdc, 0xd0, 0xee, 0xb5, 0xd1,
	0x85, 0xd7, 0x1e, 0xf4, 0xa7, 0x64, 0x90, 0x01, 0x4d, 0x33, 0x6e, 0x9c, 0x49, 0x59, 0x9d, 0x86,
	0xbf, 0xce, 0x88, 0x71, 0x9a, 0x84, 0x25, 0x2b, 0x10, 0x74, 0xeb, 0x28, 0xca, 0xbd, 0xd8, 0xae,
	0xac, 0x56, 0xe8, 0x52, 0x27, 0xe4, 0xea, 0xf0, 0xe6, 0x6d, 0xb6, 0x7b, 0xbb, 0x5d, 0x59, 0x47,
	0xba, 0x77, 0xc9, 0xf6, 0xe9, 0xba, 0x4d, 0x9e, 0x24, 0x00, 0xfe, 0x82, 0xf2, 0x2c, 0x83, 0x3c,
	0xf6, 0x71, 0x41, 0x79, 0x94, 0x19, 0xe7, 0xf2, 0x5e, 0x8f, 0x13, 0x80, 0xaf, 0x6a, 0x32, 0x95,
	0x03, 0x7d, 0x44, 0x6e, 0x1b, 0x1e, 0x4b, 0x28, 0x78, 0x07, 0x3f, 0x92, 0xf0, 0x4d, 0x02, 0x30,
	0x6d, 0x64, 0x45, 0xbe, 0x22, 0x37, 0x28, 0xaa, 0x32, 0x17, 0xd8, 0x71, 0x7d, 0xc9, 0x5d, 0x2b,
	0x55, 0x61, 0x6f, 0x89, 0x15, 0xd7, 0x45, 0x30, 0xa3, 0x91, 0x3f, 0x13, 0x39, 0xa7, 0x65, 0x4e,
	0xa1, 0xf2, 0xc3, 0x00, 0x29, 0xfa, 0x25, 0xa3, 0x05, 0x47, 0x63, 0x20, 0x7d, 0x2f, 0x15, 0xf6,
	0x61, 0x47, 0xb9, 0x0d, 0xf4, 0x49, 0x32, 0xc3, 0xf1, 0x69, 0x73, 0xd8, 0x3d, 0xc2, 0xbe, 0x6e,
	0xed, 0xa8, 0xee, 0x80, 0x3c, 0xff, 0x8f, 0x47, 0xd5, 0xfd, 0x86, 0x5c, 0x1f, 0xb6, 0x86, 0x86,
	0x76, 0x7f, 0x3e, 0xba, 0x1c, 0x5b, 0xb6, 0xdc, 0x04, 0xfb, 0xa1, 0x67, 0xf2, 0xae, 0x0e, 0xda,
	0x45, 0xf7, 0xcb, 0xef, 0xb5, 0xa9, 0x2d, 0xd7, 0xa6, 0xf6, 0x77, 0x6d, 0x6a, 0x3f, 0x37, 0x66,
	0x6f, 0xb9, 0x31, 0x7b, 0x7f, 0x36, 0x66, 0xef, 0xdb, 0xeb, 0x94, 0xf2, 0x4c, 0x84, 0x76, 0xc4,
	0x66, 0x4e, 0xdb, 0x4f, 0x5e, 0xcb, 0x75, 0x8a, 0x58, 0xbe, 0x13, 0x0a, 0x16, 0x83, 0xf3, 0x7d,
	0xe2, 0xfc, 0xd8, 0x29, 0x8e, 0xfc, 0x7d, 0x38, 0x90, 0xe8, 0xe4, 0x5f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xdb, 0x11, 0x14, 0xf7, 0xb8, 0x02, 0x00, 0x00,
}

func (m *QueryOutboundFeeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryOutboundFeeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryOutboundFeeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Height) > 0 {
		i -= len(m.Height)
		copy(dAtA[i:], m.Height)
		i = encodeVarintQueryOutboundFee(dAtA, i, uint64(len(m.Height)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Asset) > 0 {
		i -= len(m.Asset)
		copy(dAtA[i:], m.Asset)
		i = encodeVarintQueryOutboundFee(dAtA, i, uint64(len(m.Asset)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryOutboundFeeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryOutboundFeeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryOutboundFeeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DynamicMultiplierBasisPoints) > 0 {
		i -= len(m.DynamicMultiplierBasisPoints)
		copy(dAtA[i:], m.DynamicMultiplierBasisPoints)
		i = encodeVarintQueryOutboundFee(dAtA, i, uint64(len(m.DynamicMultiplierBasisPoints)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.SurplusSwitch) > 0 {
		i -= len(m.SurplusSwitch)
		copy(dAtA[i:], m.SurplusSwitch)
		i = encodeVarintQueryOutboundFee(dAtA, i, uint64(len(m.SurplusSwitch)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.FeeSpentSwitch) > 0 {
		i -= len(m.FeeSpentSwitch)
		copy(dAtA[i:], m.FeeSpentSwitch)
		i = encodeVarintQueryOutboundFee(dAtA, i, uint64(len(m.FeeSpentSwitch)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.FeeWithheldSwitch) > 0 {
		i -= len(m.FeeWithheldSwitch)
		copy(dAtA[i:], m.FeeWithheldSwitch)
		i = encodeVarintQueryOutboundFee(dAtA, i, uint64(len(m.FeeWithheldSwitch)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.OutboundFee) > 0 {
		i -= len(m.OutboundFee)
		copy(dAtA[i:], m.OutboundFee)
		i = encodeVarintQueryOutboundFee(dAtA, i, uint64(len(m.OutboundFee)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Asset) > 0 {
		i -= len(m.Asset)
		copy(dAtA[i:], m.Asset)
		i = encodeVarintQueryOutboundFee(dAtA, i, uint64(len(m.Asset)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryOutboundFeesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryOutboundFeesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryOutboundFeesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Height) > 0 {
		i -= len(m.Height)
		copy(dAtA[i:], m.Height)
		i = encodeVarintQueryOutboundFee(dAtA, i, uint64(len(m.Height)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryOutboundFeesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryOutboundFeesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryOutboundFeesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OutboundFees) > 0 {
		for iNdEx := len(m.OutboundFees) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OutboundFees[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQueryOutboundFee(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQueryOutboundFee(dAtA []byte, offset int, v uint64) int {
	offset -= sovQueryOutboundFee(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryOutboundFeeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Asset)
	if l > 0 {
		n += 1 + l + sovQueryOutboundFee(uint64(l))
	}
	l = len(m.Height)
	if l > 0 {
		n += 1 + l + sovQueryOutboundFee(uint64(l))
	}
	return n
}

func (m *QueryOutboundFeeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Asset)
	if l > 0 {
		n += 1 + l + sovQueryOutboundFee(uint64(l))
	}
	l = len(m.OutboundFee)
	if l > 0 {
		n += 1 + l + sovQueryOutboundFee(uint64(l))
	}
	l = len(m.FeeWithheldSwitch)
	if l > 0 {
		n += 1 + l + sovQueryOutboundFee(uint64(l))
	}
	l = len(m.FeeSpentSwitch)
	if l > 0 {
		n += 1 + l + sovQueryOutboundFee(uint64(l))
	}
	l = len(m.SurplusSwitch)
	if l > 0 {
		n += 1 + l + sovQueryOutboundFee(uint64(l))
	}
	l = len(m.DynamicMultiplierBasisPoints)
	if l > 0 {
		n += 1 + l + sovQueryOutboundFee(uint64(l))
	}
	return n
}

func (m *QueryOutboundFeesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Height)
	if l > 0 {
		n += 1 + l + sovQueryOutboundFee(uint64(l))
	}
	return n
}

func (m *QueryOutboundFeesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.OutboundFees) > 0 {
		for _, e := range m.OutboundFees {
			l = e.Size()
			n += 1 + l + sovQueryOutboundFee(uint64(l))
		}
	}
	return n
}

func sovQueryOutboundFee(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQueryOutboundFee(x uint64) (n int) {
	return sovQueryOutboundFee(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryOutboundFeeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQueryOutboundFee
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryOutboundFeeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryOutboundFeeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryOutboundFee
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryOutboundFee
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryOutboundFee
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Asset = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryOutboundFee
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryOutboundFee
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryOutboundFee
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Height = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQueryOutboundFee(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQueryOutboundFee
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryOutboundFeeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQueryOutboundFee
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryOutboundFeeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryOutboundFeeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryOutboundFee
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryOutboundFee
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryOutboundFee
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Asset = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutboundFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryOutboundFee
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryOutboundFee
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryOutboundFee
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OutboundFee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeWithheldSwitch", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryOutboundFee
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryOutboundFee
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryOutboundFee
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeWithheldSwitch = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeSpentSwitch", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryOutboundFee
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryOutboundFee
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryOutboundFee
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeSpentSwitch = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SurplusSwitch", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryOutboundFee
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryOutboundFee
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryOutboundFee
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SurplusSwitch = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DynamicMultiplierBasisPoints", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryOutboundFee
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryOutboundFee
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryOutboundFee
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DynamicMultiplierBasisPoints = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQueryOutboundFee(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQueryOutboundFee
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryOutboundFeesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQueryOutboundFee
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryOutboundFeesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryOutboundFeesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryOutboundFee
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQueryOutboundFee
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQueryOutboundFee
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Height = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQueryOutboundFee(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQueryOutboundFee
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryOutboundFeesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQueryOutboundFee
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryOutboundFeesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryOutboundFeesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutboundFees", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryOutboundFee
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQueryOutboundFee
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQueryOutboundFee
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OutboundFees = append(m.OutboundFees, &QueryOutboundFeeResponse{})
			if err := m.OutboundFees[len(m.OutboundFees)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQueryOutboundFee(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQueryOutboundFee
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQueryOutboundFee(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQueryOutboundFee
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQueryOutboundFee
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQueryOutboundFee
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQueryOutboundFee
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQueryOutboundFee
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQueryOutboundFee
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQueryOutboundFee        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQueryOutboundFee          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQueryOutboundFee = fmt.Errorf("proto: unexpected end of group")
)
