// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types/type_liquidity_provider.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/switchlyprotocol/switchlynode/v3/common"
	github_com_switchlyprotocol_switchlynode_v3_common "github.com/switchlyprotocol/switchlynode/v3/common"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type LiquidityProvider struct {
	Asset              github_com_switchlyprotocol_switchlynode_v3_common.Asset   `protobuf:"bytes,1,opt,name=asset,proto3,customtype=github.com/switchlyprotocol/switchlynode/v3/common.Asset" json:"asset"`
	SwitchAddress      github_com_switchlyprotocol_switchlynode_v3_common.Address `protobuf:"bytes,2,opt,name=switch_address,json=switchAddress,proto3,casttype=github.com/switchlyprotocol/switchlynode/v3/common.Address" json:"switch_address,omitempty"`
	AssetAddress       github_com_switchlyprotocol_switchlynode_v3_common.Address `protobuf:"bytes,3,opt,name=asset_address,json=assetAddress,proto3,casttype=github.com/switchlyprotocol/switchlynode/v3/common.Address" json:"asset_address,omitempty"`
	LastAddHeight      int64                                                      `protobuf:"varint,4,opt,name=last_add_height,json=lastAddHeight,proto3" json:"last_add_height,omitempty"`
	LastWithdrawHeight int64                                                      `protobuf:"varint,5,opt,name=last_withdraw_height,json=lastWithdrawHeight,proto3" json:"last_withdraw_height,omitempty"`
	Units              cosmossdk_io_math.Uint                                     `protobuf:"bytes,6,opt,name=units,proto3,customtype=cosmossdk.io/math.Uint" json:"units"`
	PendingSwitch      cosmossdk_io_math.Uint                                     `protobuf:"bytes,7,opt,name=pending_switch,json=pendingSwitch,proto3,customtype=cosmossdk.io/math.Uint" json:"pending_switch"`
	PendingAsset       cosmossdk_io_math.Uint                                     `protobuf:"bytes,8,opt,name=pending_asset,json=pendingAsset,proto3,customtype=cosmossdk.io/math.Uint" json:"pending_asset"`
	PendingTxID        github_com_switchlyprotocol_switchlynode_v3_common.TxID    `protobuf:"bytes,9,opt,name=pending_tx_Id,json=pendingTxId,proto3,casttype=github.com/switchlyprotocol/switchlynode/v3/common.TxID" json:"pending_tx_Id,omitempty"`
	SwitchDepositValue cosmossdk_io_math.Uint                                     `protobuf:"bytes,10,opt,name=switch_deposit_value,json=switchDepositValue,proto3,customtype=cosmossdk.io/math.Uint" json:"switch_deposit_value"`
	AssetDepositValue  cosmossdk_io_math.Uint                                     `protobuf:"bytes,11,opt,name=asset_deposit_value,json=assetDepositValue,proto3,customtype=cosmossdk.io/math.Uint" json:"asset_deposit_value"`
}

func (m *LiquidityProvider) Reset()         { *m = LiquidityProvider{} }
func (m *LiquidityProvider) String() string { return proto.CompactTextString(m) }
func (*LiquidityProvider) ProtoMessage()    {}
func (*LiquidityProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_8035bc1d3a7a7d7d, []int{0}
}
func (m *LiquidityProvider) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LiquidityProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LiquidityProvider.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LiquidityProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidityProvider.Merge(m, src)
}
func (m *LiquidityProvider) XXX_Size() int {
	return m.Size()
}
func (m *LiquidityProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidityProvider.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidityProvider proto.InternalMessageInfo

func (m *LiquidityProvider) GetSwitchAddress() github_com_switchlyprotocol_switchlynode_v3_common.Address {
	if m != nil {
		return m.SwitchAddress
	}
	return ""
}

func (m *LiquidityProvider) GetAssetAddress() github_com_switchlyprotocol_switchlynode_v3_common.Address {
	if m != nil {
		return m.AssetAddress
	}
	return ""
}

func (m *LiquidityProvider) GetLastAddHeight() int64 {
	if m != nil {
		return m.LastAddHeight
	}
	return 0
}

func (m *LiquidityProvider) GetLastWithdrawHeight() int64 {
	if m != nil {
		return m.LastWithdrawHeight
	}
	return 0
}

func (m *LiquidityProvider) GetPendingTxID() github_com_switchlyprotocol_switchlynode_v3_common.TxID {
	if m != nil {
		return m.PendingTxID
	}
	return ""
}

func init() {
	proto.RegisterType((*LiquidityProvider)(nil), "types.LiquidityProvider")
}

func init() {
	proto.RegisterFile("types/type_liquidity_provider.proto", fileDescriptor_8035bc1d3a7a7d7d)
}

var fileDescriptor_8035bc1d3a7a7d7d = []byte{
	// 482 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0x1b, 0x46, 0x0b, 0x73, 0x97, 0xa1, 0x79, 0x15, 0x8a, 0x76, 0x48, 0x2a, 0x90, 0x50,
	0x4f, 0x0d, 0x62, 0x48, 0x20, 0x84, 0x10, 0x2b, 0x43, 0x62, 0x08, 0xa1, 0x2a, 0xc0, 0x90, 0xb8,
	0x44, 0x59, 0x6c, 0x25, 0x16, 0x69, 0x1c, 0x62, 0xf7, 0xdf, 0xb7, 0xe0, 0x63, 0xed, 0xb8, 0x23,
	0xe2, 0x10, 0xa1, 0xf6, 0x2b, 0x70, 0xda, 0x09, 0xf9, 0xb5, 0x5b, 0xc6, 0x2d, 0x54, 0xbb, 0xb4,
	0xce, 0xf3, 0x3e, 0xcf, 0xef, 0x75, 0xec, 0x57, 0x41, 0xf7, 0xe5, 0xbc, 0xa0, 0xc2, 0x57, 0xbf,
	0x61, 0xc6, 0xbe, 0x8d, 0x19, 0x61, 0x72, 0x1e, 0x16, 0x25, 0x9f, 0x30, 0x42, 0xcb, 0x7e, 0x51,
	0x72, 0xc9, 0x71, 0x13, 0x4c, 0x07, 0xfb, 0x31, 0x1f, 0x8d, 0x78, 0xee, 0xeb, 0x3f, 0x5d, 0x3b,
	0xe8, 0x24, 0x3c, 0xe1, 0xb0, 0xf4, 0xd5, 0x4a, 0xab, 0xf7, 0x7e, 0xb7, 0xd0, 0xde, 0xbb, 0x15,
	0x6e, 0x68, 0x68, 0x98, 0xa2, 0x66, 0x24, 0x04, 0x95, 0x8e, 0xd5, 0xb5, 0x7a, 0xed, 0x47, 0x76,
	0xdf, 0x90, 0x8e, 0x94, 0x38, 0x78, 0x79, 0x5e, 0x79, 0x8d, 0x9f, 0x95, 0xf7, 0x34, 0x61, 0x32,
	0x1d, 0x9f, 0xa9, 0xa2, 0x2f, 0xa6, 0x4c, 0xc6, 0x69, 0x36, 0x07, 0x6a, 0xcc, 0xb3, 0xb5, 0x90,
	0x73, 0x42, 0xfd, 0xc9, 0xa1, 0x7f, 0x95, 0x10, 0x68, 0x3a, 0xa6, 0x68, 0x57, 0xdb, 0xc2, 0x88,
	0x90, 0x92, 0x0a, 0xe1, 0xdc, 0xe8, 0x5a, 0xbd, 0xed, 0xc1, 0x8b, 0xcb, 0xca, 0x7b, 0xb6, 0x09,
	0x5c, 0x53, 0x02, 0x5b, 0xd7, 0xcd, 0x23, 0x8e, 0x91, 0x0d, 0xfd, 0xd6, 0x5d, 0xb6, 0xae, 0xa5,
	0xcb, 0x0e, 0x40, 0x57, 0x4d, 0x1e, 0xa0, 0x3b, 0x59, 0x24, 0xa0, 0x47, 0x98, 0x52, 0x96, 0xa4,
	0xd2, 0xb9, 0xd9, 0xb5, 0x7a, 0x5b, 0x81, 0xad, 0xe4, 0x23, 0x42, 0xde, 0x80, 0x88, 0x1f, 0xa2,
	0x0e, 0xf8, 0xa6, 0x4c, 0xa6, 0xa4, 0x8c, 0xa6, 0x2b, 0x73, 0x13, 0xcc, 0x58, 0xd5, 0x3e, 0x9b,
	0x92, 0x49, 0x3c, 0x46, 0xcd, 0x71, 0xce, 0xa4, 0x70, 0x5a, 0xb0, 0x6d, 0xd7, 0x9c, 0xfe, 0xdd,
	0x98, 0x8b, 0x11, 0x17, 0x82, 0x7c, 0xed, 0x33, 0xee, 0x8f, 0x22, 0x99, 0xf6, 0x3f, 0xb1, 0x5c,
	0x06, 0xda, 0x8c, 0x5f, 0xa3, 0xdd, 0x82, 0xe6, 0x84, 0xe5, 0x49, 0xa8, 0xdf, 0xc3, 0xb9, 0x55,
	0x2b, 0x6e, 0x9b, 0xd4, 0x07, 0x08, 0xe1, 0x57, 0x68, 0x25, 0x84, 0x7a, 0x22, 0x6e, 0xd7, 0xa2,
	0xec, 0x98, 0x10, 0x5c, 0x37, 0xce, 0xff, 0x42, 0xe4, 0x2c, 0x3c, 0x21, 0xce, 0x36, 0x40, 0xde,
	0x2e, 0x2a, 0xaf, 0x3d, 0xd4, 0x85, 0x8f, 0xb3, 0x93, 0xe3, 0xcb, 0xca, 0x7b, 0xb2, 0xc1, 0x7d,
	0xa8, 0x68, 0xd0, 0x2e, 0xd6, 0x1c, 0x82, 0x87, 0xa8, 0x63, 0xe6, 0x8a, 0xd0, 0x82, 0x0b, 0x26,
	0xc3, 0x49, 0x94, 0x8d, 0xa9, 0x83, 0x6a, 0xed, 0x1d, 0xeb, 0xec, 0xb1, 0x8e, 0x9e, 0xaa, 0x24,
	0x7e, 0x8f, 0xf6, 0xf5, 0x08, 0xfd, 0x0b, 0x6c, 0xd7, 0x02, 0xee, 0x41, 0xf4, 0x2a, 0x6f, 0x70,
	0x7a, 0xbe, 0x70, 0xad, 0x8b, 0x85, 0x6b, 0xfd, 0x5a, 0xb8, 0xd6, 0xf7, 0xa5, 0xdb, 0xb8, 0x58,
	0xba, 0x8d, 0x1f, 0x4b, 0xb7, 0xf1, 0xe5, 0xf9, 0xff, 0x9c, 0xc0, 0x6c, 0xad, 0xc0, 0x87, 0x41,
	0x9c, 0xb5, 0xc0, 0x7a, 0xf8, 0x27, 0x00, 0x00, 0xff, 0xff, 0x21, 0x0d, 0xd3, 0x54, 0x2e, 0x04,
	0x00, 0x00,
}

func (m *LiquidityProvider) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LiquidityProvider) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LiquidityProvider) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.AssetDepositValue.Size()
		i -= size
		if _, err := m.AssetDepositValue.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypeLiquidityProvider(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x5a
	{
		size := m.SwitchDepositValue.Size()
		i -= size
		if _, err := m.SwitchDepositValue.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypeLiquidityProvider(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	if len(m.PendingTxID) > 0 {
		i -= len(m.PendingTxID)
		copy(dAtA[i:], m.PendingTxID)
		i = encodeVarintTypeLiquidityProvider(dAtA, i, uint64(len(m.PendingTxID)))
		i--
		dAtA[i] = 0x4a
	}
	{
		size := m.PendingAsset.Size()
		i -= size
		if _, err := m.PendingAsset.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypeLiquidityProvider(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size := m.PendingSwitch.Size()
		i -= size
		if _, err := m.PendingSwitch.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypeLiquidityProvider(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.Units.Size()
		i -= size
		if _, err := m.Units.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypeLiquidityProvider(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if m.LastWithdrawHeight != 0 {
		i = encodeVarintTypeLiquidityProvider(dAtA, i, uint64(m.LastWithdrawHeight))
		i--
		dAtA[i] = 0x28
	}
	if m.LastAddHeight != 0 {
		i = encodeVarintTypeLiquidityProvider(dAtA, i, uint64(m.LastAddHeight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.AssetAddress) > 0 {
		i -= len(m.AssetAddress)
		copy(dAtA[i:], m.AssetAddress)
		i = encodeVarintTypeLiquidityProvider(dAtA, i, uint64(len(m.AssetAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SwitchAddress) > 0 {
		i -= len(m.SwitchAddress)
		copy(dAtA[i:], m.SwitchAddress)
		i = encodeVarintTypeLiquidityProvider(dAtA, i, uint64(len(m.SwitchAddress)))
		i--
		dAtA[i] = 0x12
	}
	{
		size := m.Asset.Size()
		i -= size
		if _, err := m.Asset.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypeLiquidityProvider(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintTypeLiquidityProvider(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypeLiquidityProvider(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LiquidityProvider) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Asset.Size()
	n += 1 + l + sovTypeLiquidityProvider(uint64(l))
	l = len(m.SwitchAddress)
	if l > 0 {
		n += 1 + l + sovTypeLiquidityProvider(uint64(l))
	}
	l = len(m.AssetAddress)
	if l > 0 {
		n += 1 + l + sovTypeLiquidityProvider(uint64(l))
	}
	if m.LastAddHeight != 0 {
		n += 1 + sovTypeLiquidityProvider(uint64(m.LastAddHeight))
	}
	if m.LastWithdrawHeight != 0 {
		n += 1 + sovTypeLiquidityProvider(uint64(m.LastWithdrawHeight))
	}
	l = m.Units.Size()
	n += 1 + l + sovTypeLiquidityProvider(uint64(l))
	l = m.PendingSwitch.Size()
	n += 1 + l + sovTypeLiquidityProvider(uint64(l))
	l = m.PendingAsset.Size()
	n += 1 + l + sovTypeLiquidityProvider(uint64(l))
	l = len(m.PendingTxID)
	if l > 0 {
		n += 1 + l + sovTypeLiquidityProvider(uint64(l))
	}
	l = m.SwitchDepositValue.Size()
	n += 1 + l + sovTypeLiquidityProvider(uint64(l))
	l = m.AssetDepositValue.Size()
	n += 1 + l + sovTypeLiquidityProvider(uint64(l))
	return n
}

func sovTypeLiquidityProvider(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypeLiquidityProvider(x uint64) (n int) {
	return sovTypeLiquidityProvider(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LiquidityProvider) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypeLiquidityProvider
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LiquidityProvider: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LiquidityProvider: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeLiquidityProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypeLiquidityProvider
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypeLiquidityProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Asset.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwitchAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeLiquidityProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeLiquidityProvider
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeLiquidityProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SwitchAddress = github_com_switchlyprotocol_switchlynode_v3_common.Address(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeLiquidityProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeLiquidityProvider
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeLiquidityProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetAddress = github_com_switchlyprotocol_switchlynode_v3_common.Address(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastAddHeight", wireType)
			}
			m.LastAddHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeLiquidityProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastAddHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastWithdrawHeight", wireType)
			}
			m.LastWithdrawHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeLiquidityProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastWithdrawHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Units", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeLiquidityProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeLiquidityProvider
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeLiquidityProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Units.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingSwitch", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeLiquidityProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeLiquidityProvider
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeLiquidityProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PendingSwitch.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingAsset", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeLiquidityProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeLiquidityProvider
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeLiquidityProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PendingAsset.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingTxID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeLiquidityProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeLiquidityProvider
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeLiquidityProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingTxID = github_com_switchlyprotocol_switchlynode_v3_common.TxID(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwitchDepositValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeLiquidityProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeLiquidityProvider
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeLiquidityProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SwitchDepositValue.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetDepositValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeLiquidityProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeLiquidityProvider
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeLiquidityProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AssetDepositValue.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypeLiquidityProvider(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypeLiquidityProvider
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypeLiquidityProvider(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypeLiquidityProvider
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypeLiquidityProvider
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypeLiquidityProvider
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypeLiquidityProvider
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypeLiquidityProvider
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypeLiquidityProvider
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypeLiquidityProvider        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypeLiquidityProvider          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypeLiquidityProvider = fmt.Errorf("proto: unexpected end of group")
)
